/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookMetadataDto {
    #[serde(rename = "authors")]
    pub authors: Vec<models::AuthorDto>,
    #[serde(rename = "authorsLock")]
    pub authors_lock: bool,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "isbn")]
    pub isbn: String,
    #[serde(rename = "isbnLock")]
    pub isbn_lock: bool,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "links")]
    pub links: Vec<models::WebLinkDto>,
    #[serde(rename = "linksLock")]
    pub links_lock: bool,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "numberLock")]
    pub number_lock: bool,
    #[serde(rename = "numberSort")]
    pub number_sort: f32,
    #[serde(rename = "numberSortLock")]
    pub number_sort_lock: bool,
    #[serde(rename = "releaseDate", skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    #[serde(rename = "releaseDateLock")]
    pub release_date_lock: bool,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "summaryLock")]
    pub summary_lock: bool,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "tagsLock")]
    pub tags_lock: bool,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "titleLock")]
    pub title_lock: bool,
}

impl BookMetadataDto {
    pub fn new(authors: Vec<models::AuthorDto>, authors_lock: bool, created: String, isbn: String, isbn_lock: bool, last_modified: String, links: Vec<models::WebLinkDto>, links_lock: bool, number: String, number_lock: bool, number_sort: f32, number_sort_lock: bool, release_date_lock: bool, summary: String, summary_lock: bool, tags: Vec<String>, tags_lock: bool, title: String, title_lock: bool) -> BookMetadataDto {
        BookMetadataDto {
            authors,
            authors_lock,
            created,
            isbn,
            isbn_lock,
            last_modified,
            links,
            links_lock,
            number,
            number_lock,
            number_sort,
            number_sort_lock,
            release_date: None,
            release_date_lock,
            summary,
            summary_lock,
            tags,
            tags_lock,
            title,
            title_lock,
        }
    }
}

