/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookDto {
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "fileHash")]
    pub file_hash: String,
    #[serde(rename = "fileLastModified")]
    pub file_last_modified: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "libraryId")]
    pub library_id: String,
    #[serde(rename = "media")]
    pub media: Box<models::MediaDto>,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::BookMetadataDto>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "oneshot")]
    pub oneshot: bool,
    #[serde(rename = "readProgress", skip_serializing_if = "Option::is_none")]
    pub read_progress: Option<Box<models::ReadProgressDto>>,
    #[serde(rename = "seriesId")]
    pub series_id: String,
    #[serde(rename = "seriesTitle")]
    pub series_title: String,
    #[serde(rename = "size")]
    pub size: String,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: i64,
    #[serde(rename = "url")]
    pub url: String,
}

impl BookDto {
    pub fn new(created: String, deleted: bool, file_hash: String, file_last_modified: String, id: String, last_modified: String, library_id: String, media: models::MediaDto, metadata: models::BookMetadataDto, name: String, number: i32, oneshot: bool, series_id: String, series_title: String, size: String, size_bytes: i64, url: String) -> BookDto {
        BookDto {
            created,
            deleted,
            file_hash,
            file_last_modified,
            id,
            last_modified,
            library_id,
            media: Box::new(media),
            metadata: Box::new(metadata),
            name,
            number,
            oneshot,
            read_progress: None,
            series_id,
            series_title,
            size,
            size_bytes,
            url,
        }
    }
}

