/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeriesDto {
    #[serde(rename = "booksCount")]
    pub books_count: i32,
    #[serde(rename = "booksInProgressCount")]
    pub books_in_progress_count: i32,
    #[serde(rename = "booksMetadata")]
    pub books_metadata: Box<models::BookMetadataAggregationDto>,
    #[serde(rename = "booksReadCount")]
    pub books_read_count: i32,
    #[serde(rename = "booksUnreadCount")]
    pub books_unread_count: i32,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "fileLastModified")]
    pub file_last_modified: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "lastModified")]
    pub last_modified: String,
    #[serde(rename = "libraryId")]
    pub library_id: String,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::SeriesMetadataDto>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "oneshot")]
    pub oneshot: bool,
    #[serde(rename = "url")]
    pub url: String,
}

impl SeriesDto {
    pub fn new(books_count: i32, books_in_progress_count: i32, books_metadata: models::BookMetadataAggregationDto, books_read_count: i32, books_unread_count: i32, created: String, deleted: bool, file_last_modified: String, id: String, last_modified: String, library_id: String, metadata: models::SeriesMetadataDto, name: String, oneshot: bool, url: String) -> SeriesDto {
        SeriesDto {
            books_count,
            books_in_progress_count,
            books_metadata: Box::new(books_metadata),
            books_read_count,
            books_unread_count,
            created,
            deleted,
            file_last_modified,
            id,
            last_modified,
            library_id,
            metadata: Box::new(metadata),
            name,
            oneshot,
            url,
        }
    }
}

