/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SeriesMetadataUpdateDto : Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeriesMetadataUpdateDto {
    #[serde(rename = "ageRating", skip_serializing_if = "Option::is_none")]
    pub age_rating: Option<i32>,
    #[serde(rename = "ageRatingLock", skip_serializing_if = "Option::is_none")]
    pub age_rating_lock: Option<bool>,
    #[serde(rename = "alternateTitles", skip_serializing_if = "Option::is_none")]
    pub alternate_titles: Option<Vec<models::AlternateTitleUpdateDto>>,
    #[serde(rename = "alternateTitlesLock", skip_serializing_if = "Option::is_none")]
    pub alternate_titles_lock: Option<bool>,
    #[serde(rename = "genres", skip_serializing_if = "Option::is_none")]
    pub genres: Option<Vec<String>>,
    #[serde(rename = "genresLock", skip_serializing_if = "Option::is_none")]
    pub genres_lock: Option<bool>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "languageLock", skip_serializing_if = "Option::is_none")]
    pub language_lock: Option<bool>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::WebLinkUpdateDto>>,
    #[serde(rename = "linksLock", skip_serializing_if = "Option::is_none")]
    pub links_lock: Option<bool>,
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<String>,
    #[serde(rename = "publisherLock", skip_serializing_if = "Option::is_none")]
    pub publisher_lock: Option<bool>,
    #[serde(rename = "readingDirection", skip_serializing_if = "Option::is_none")]
    pub reading_direction: Option<ReadingDirection>,
    #[serde(rename = "readingDirectionLock", skip_serializing_if = "Option::is_none")]
    pub reading_direction_lock: Option<bool>,
    #[serde(rename = "sharingLabels", skip_serializing_if = "Option::is_none")]
    pub sharing_labels: Option<Vec<String>>,
    #[serde(rename = "sharingLabelsLock", skip_serializing_if = "Option::is_none")]
    pub sharing_labels_lock: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "statusLock", skip_serializing_if = "Option::is_none")]
    pub status_lock: Option<bool>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(rename = "summaryLock", skip_serializing_if = "Option::is_none")]
    pub summary_lock: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "tagsLock", skip_serializing_if = "Option::is_none")]
    pub tags_lock: Option<bool>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "titleLock", skip_serializing_if = "Option::is_none")]
    pub title_lock: Option<bool>,
    #[serde(rename = "titleSort", skip_serializing_if = "Option::is_none")]
    pub title_sort: Option<String>,
    #[serde(rename = "titleSortLock", skip_serializing_if = "Option::is_none")]
    pub title_sort_lock: Option<bool>,
    #[serde(rename = "totalBookCount", skip_serializing_if = "Option::is_none")]
    pub total_book_count: Option<i32>,
    #[serde(rename = "totalBookCountLock", skip_serializing_if = "Option::is_none")]
    pub total_book_count_lock: Option<bool>,
}

impl SeriesMetadataUpdateDto {
    /// Metadata fields to update. Set a field to null to unset the metadata. You can omit fields you don't want to update.
    pub fn new() -> SeriesMetadataUpdateDto {
        SeriesMetadataUpdateDto {
            age_rating: None,
            age_rating_lock: None,
            alternate_titles: None,
            alternate_titles_lock: None,
            genres: None,
            genres_lock: None,
            language: None,
            language_lock: None,
            links: None,
            links_lock: None,
            publisher: None,
            publisher_lock: None,
            reading_direction: None,
            reading_direction_lock: None,
            sharing_labels: None,
            sharing_labels_lock: None,
            status: None,
            status_lock: None,
            summary: None,
            summary_lock: None,
            tags: None,
            tags_lock: None,
            title: None,
            title_lock: None,
            title_sort: None,
            title_sort_lock: None,
            total_book_count: None,
            total_book_count_lock: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReadingDirection {
    #[serde(rename = "LEFT_TO_RIGHT")]
    LeftToRight,
    #[serde(rename = "RIGHT_TO_LEFT")]
    RightToLeft,
    #[serde(rename = "VERTICAL")]
    Vertical,
    #[serde(rename = "WEBTOON")]
    Webtoon,
}

impl Default for ReadingDirection {
    fn default() -> ReadingDirection {
        Self::LeftToRight
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ENDED")]
    Ended,
    #[serde(rename = "ONGOING")]
    Ongoing,
    #[serde(rename = "ABANDONED")]
    Abandoned,
    #[serde(rename = "HIATUS")]
    Hiatus,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ended
    }
}

