/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsDto {
    #[serde(rename = "deleteEmptyCollections")]
    pub delete_empty_collections: bool,
    #[serde(rename = "deleteEmptyReadLists")]
    pub delete_empty_read_lists: bool,
    #[serde(rename = "kepubifyPath")]
    pub kepubify_path: Box<models::SettingMultiSourceString>,
    #[serde(rename = "koboPort", skip_serializing_if = "Option::is_none")]
    pub kobo_port: Option<i32>,
    #[serde(rename = "koboProxy")]
    pub kobo_proxy: bool,
    #[serde(rename = "rememberMeDurationDays")]
    pub remember_me_duration_days: i64,
    #[serde(rename = "serverContextPath")]
    pub server_context_path: Box<models::SettingMultiSourceString>,
    #[serde(rename = "serverPort")]
    pub server_port: Box<models::SettingMultiSourceInteger>,
    #[serde(rename = "taskPoolSize")]
    pub task_pool_size: i32,
    #[serde(rename = "thumbnailSize")]
    pub thumbnail_size: ThumbnailSize,
}

impl SettingsDto {
    pub fn new(delete_empty_collections: bool, delete_empty_read_lists: bool, kepubify_path: models::SettingMultiSourceString, kobo_proxy: bool, remember_me_duration_days: i64, server_context_path: models::SettingMultiSourceString, server_port: models::SettingMultiSourceInteger, task_pool_size: i32, thumbnail_size: ThumbnailSize) -> SettingsDto {
        SettingsDto {
            delete_empty_collections,
            delete_empty_read_lists,
            kepubify_path: Box::new(kepubify_path),
            kobo_port: None,
            kobo_proxy,
            remember_me_duration_days,
            server_context_path: Box::new(server_context_path),
            server_port: Box::new(server_port),
            task_pool_size,
            thumbnail_size,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ThumbnailSize {
    #[serde(rename = "DEFAULT")]
    Default,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "LARGE")]
    Large,
    #[serde(rename = "XLARGE")]
    Xlarge,
}

impl Default for ThumbnailSize {
    fn default() -> ThumbnailSize {
        Self::Default
    }
}

