/*
 * Komga API
 *
 * Komga REST API.  ## Reference  Check the API reference: - on the [Komga website](https://komga.org/docs/openapi/komga-api) - on any running Komga instance at `/swagger-ui.html` - on [GitHub](https://raw.githubusercontent.com/gotson/komga/refs/heads/master/komga/docs/openapi.json)  ## Authentication  Most endpoints require authentication. Authentication is done using either: - Basic Authentication - Passing an API Key in the `X-API-Key` header  ## Sessions  Upon successful authentication, a session is created, and can be reused.  - By default, a `KOMGA-SESSION` cookie is set via `Set-Cookie` response header. This works well for browsers and clients that can handle cookies. - If you specify a header `X-Auth-Token` during authentication, the session ID will be returned via this same header. You can then pass that header again for subsequent requests to reuse the session.  If you need to set the session cookie later on, you can call `/api/v1/login/set-cookie` with `X-Auth-Token`. The response will contain the `Set-Cookie` header.  ## Remember Me  During authentication, if a request parameter `remember-me` is passed and set to `true`, the server will also return a `komga-remember-me` cookie. This cookie will be used to login automatically even if the session has expired.  ## Logout  You can explicitly logout an existing session by calling `/api/logout`. This would return a `204`.  ## Deprecation  API endpoints marked as deprecated will be removed in the next major version.
 *
 * The version of the OpenAPI document: 1.23.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WpMetadataDto {
    #[serde(rename = "artist")]
    pub artist: Vec<String>,
    #[serde(rename = "author")]
    pub author: Vec<String>,
    #[serde(rename = "belongsTo", skip_serializing_if = "Option::is_none")]
    pub belongs_to: Option<Box<models::WpBelongsToDto>>,
    #[serde(rename = "colorist")]
    pub colorist: Vec<String>,
    #[serde(rename = "conformsTo", skip_serializing_if = "Option::is_none")]
    pub conforms_to: Option<String>,
    #[serde(rename = "contributor")]
    pub contributor: Vec<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "editor")]
    pub editor: Vec<String>,
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    #[serde(rename = "illustrator")]
    pub illustrator: Vec<String>,
    #[serde(rename = "inker")]
    pub inker: Vec<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(rename = "letterer")]
    pub letterer: Vec<String>,
    #[serde(rename = "modified", skip_serializing_if = "Option::is_none")]
    pub modified: Option<String>,
    #[serde(rename = "numberOfPages", skip_serializing_if = "Option::is_none")]
    pub number_of_pages: Option<i32>,
    #[serde(rename = "penciler")]
    pub penciler: Vec<String>,
    #[serde(rename = "published", skip_serializing_if = "Option::is_none")]
    pub published: Option<String>,
    #[serde(rename = "publisher")]
    pub publisher: Vec<String>,
    #[serde(rename = "readingProgression", skip_serializing_if = "Option::is_none")]
    pub reading_progression: Option<ReadingProgression>,
    #[serde(rename = "rendition")]
    pub rendition: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "sortAs", skip_serializing_if = "Option::is_none")]
    pub sort_as: Option<String>,
    #[serde(rename = "subject")]
    pub subject: Vec<String>,
    #[serde(rename = "subtitle", skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "translator")]
    pub translator: Vec<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl WpMetadataDto {
    pub fn new(artist: Vec<String>, author: Vec<String>, colorist: Vec<String>, contributor: Vec<String>, editor: Vec<String>, illustrator: Vec<String>, inker: Vec<String>, letterer: Vec<String>, penciler: Vec<String>, publisher: Vec<String>, rendition: std::collections::HashMap<String, serde_json::Value>, subject: Vec<String>, title: String, translator: Vec<String>) -> WpMetadataDto {
        WpMetadataDto {
            artist,
            author,
            belongs_to: None,
            colorist,
            conforms_to: None,
            contributor,
            description: None,
            editor,
            identifier: None,
            illustrator,
            inker,
            language: None,
            letterer,
            modified: None,
            number_of_pages: None,
            penciler,
            published: None,
            publisher,
            reading_progression: None,
            rendition,
            sort_as: None,
            subject,
            subtitle: None,
            title,
            translator,
            r#type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReadingProgression {
    #[serde(rename = "rtl")]
    Rtl,
    #[serde(rename = "ltr")]
    Ltr,
    #[serde(rename = "ttb")]
    Ttb,
    #[serde(rename = "btt")]
    Btt,
    #[serde(rename = "auto")]
    Auto,
}

impl Default for ReadingProgression {
    fn default() -> ReadingProgression {
        Self::Rtl
    }
}

